# Generated by Django 5.2 on 2026-04-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='semana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
