# Generated by Django 5.2 on 2026-04-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_semana_remove_cliente_semana_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semana',
            options={},
        ),
        migrations.RemoveField(
            model_name='semana',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='semana',
            name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='semana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semana',
            name='descripcion',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
