# Generated by Django 5.2 on 2026-04-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_semana_options_remove_semana_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
