# Generated by Django 5.2 on 2026-04-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='semana',
        ),
    ]
