# Generated by Django 5.2 on 2026-04-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_remove_cliente_semana'),
    ]

    operations = [
    ]
