# Generated by Django 5.2 on 2026-04-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_auto_20260423_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='seguros',
            field=models.ManyToManyField(blank=True, related_name='doctores', to='cuentas.seguro'),
        ),
    ]
