# Generated by Django 5.2 on 2026-04-24 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_doctor_ciudad_doctor_estado_doctor_seguros'),
    ]

    operations = [
        migrations.AddField(
            model_name='necesidad',
            name='semana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necesidades', to='cuentas.semana'),
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='estado',
            field=models.CharField(choices=[('esperando', 'Esperando Cita'), ('falta_informacion', 'Falta Informacion'), ('tratado', 'Tratado')], default='esperando', max_length=20),
        ),
    ]
