# Generated by Django 5.2 on 2026-04-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_necesidad_semana_alter_necesidad_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='necesidad',
            name='doctor_especialidad',
        ),
        migrations.AlterField(
            model_name='necesidad',
            name='fecha_cita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necesidad',
            name='doctor_especialidad',
            field=models.ManyToManyField(blank=True, related_name='necesidades_especialidad', to='cuentas.doctor'),
        ),
    ]
