# Generated by Django 5.2 on 2026-04-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_remove_necesidad_doctor_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguro',
            name='numero_poliza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
